import { StyleProp, TextStyle } from 'react-native'

export const mb-#$item}: StyleProp<TextStyle>
export const mt-#$item}: StyleProp<TextStyle>
export const pb-#$item}: StyleProp<TextStyle>
export const pt-#$item}: StyleProp<TextStyle>
export const col-gap-#$item}: StyleProp<TextStyle>
export const col-gap-#$item}>div: StyleProp<TextStyle>
export const grid: StyleProp<TextStyle>
export const card: StyleProp<TextStyle>
export const card-body: StyleProp<TextStyle>
export const desc: StyleProp<TextStyle>
export const dropzone: StyleProp<TextStyle>
export const dz-message: StyleProp<TextStyle>
export const dz-button: StyleProp<TextStyle>
export const note: StyleProp<TextStyle>
export const dz-preview: StyleProp<TextStyle>
export const dz-image: StyleProp<TextStyle>
export const mb-35: StyleProp<TextStyle>
export const mt-15: StyleProp<TextStyle>
export const accordion: StyleProp<TextStyle>
export const card__header: StyleProp<TextStyle>
export const collapsed: StyleProp<TextStyle>
export const abs-link: StyleProp<TextStyle>
export const table: StyleProp<TextStyle>
export const sm: StyleProp<TextStyle>
export const action-btns: StyleProp<TextStyle>
export const download: StyleProp<TextStyle>
export const b-0: StyleProp<TextStyle>
export const nav__tabs: StyleProp<TextStyle>
export const active: StyleProp<TextStyle>
export const img-lazyloader: StyleProp<TextStyle>
export const image-hover: StyleProp<TextStyle>
export const detail-list: StyleProp<TextStyle>
export const two-columns: StyleProp<TextStyle>
export const icon: StyleProp<TextStyle>
export const area: StyleProp<TextStyle>
export const front-page: StyleProp<TextStyle>
export const progress-container: StyleProp<TextStyle>
export const progress-bar: StyleProp<TextStyle>
export const checkbox--switch: StyleProp<TextStyle>
export const custom__tooltip: StyleProp<TextStyle>
export const custom__tooltip--content: StyleProp<TextStyle>
export const mCSB_scrollTools: StyleProp<TextStyle>
export const mCSB_dragger: StyleProp<TextStyle>
export const mCSB_dragger_bar: StyleProp<TextStyle>
export const mCSB_draggerRail: StyleProp<TextStyle>
export const mCSB_draggerContainer: StyleProp<TextStyle>
export const screen__images: StyleProp<TextStyle>
export const delete: StyleProp<TextStyle>
export const bootstrap-datetimepicker-widget: StyleProp<TextStyle>
export const row: StyleProp<TextStyle>
export const col-md-6: StyleProp<TextStyle>
export const timepicker: StyleProp<TextStyle>
export const prev: StyleProp<TextStyle>
export const picker-switch: StyleProp<TextStyle>
export const day: StyleProp<TextStyle>
export const datepicker: StyleProp<TextStyle>
export const activedisabled:hover: StyleProp<TextStyle>
export const next: StyleProp<TextStyle>
export const loadmore: StyleProp<TextStyle>
export const show: StyleProp<TextStyle>
export const animate: StyleProp<TextStyle>
export const slideIn: StyleProp<TextStyle>
