import { StyleProp, TextStyle } from 'react-native'

export const inner-content: StyleProp<TextStyle>
export const card: StyleProp<TextStyle>
export const sm: StyleProp<TextStyle>
export const md: StyleProp<TextStyle>
export const lg: StyleProp<TextStyle>
export const dropdown-toggle: StyleProp<TextStyle>
export const full: StyleProp<TextStyle>
export const form-group: StyleProp<TextStyle>
export const row: StyleProp<TextStyle>
export const note: StyleProp<TextStyle>
export const transferCard: StyleProp<TextStyle>
export const ammount: StyleProp<TextStyle>
export const last-price: StyleProp<TextStyle>
export const transfer-row: StyleProp<TextStyle>
export const flex-1: StyleProp<TextStyle>
export const control-label: StyleProp<TextStyle>
export const form-control: StyleProp<TextStyle>
export const btn: StyleProp<TextStyle>
export const filter-option-inner-inner: StyleProp<TextStyle>
export const swap--convert: StyleProp<TextStyle>
export const limit: StyleProp<TextStyle>
export const card-title: StyleProp<TextStyle>
export const withdrawal: StyleProp<TextStyle>
export const label-wrapper: StyleProp<TextStyle>
export const account-sec: StyleProp<TextStyle>
export const page-title: StyleProp<TextStyle>
export const spacing-wrapper: StyleProp<TextStyle>
export const service-box: StyleProp<TextStyle>
export const video: StyleProp<TextStyle>
export const title: StyleProp<TextStyle>
export const video-icon: StyleProp<TextStyle>
export const table-head: StyleProp<TextStyle>
export const show>nav-link: StyleProp<TextStyle>
export const nav-pills: StyleProp<TextStyle>
export const nav-link: StyleProp<TextStyle>
export const activities-table: StyleProp<TextStyle>
export const rating: StyleProp<TextStyle>
export const icon: StyleProp<TextStyle>
export const green: StyleProp<TextStyle>
export const red: StyleProp<TextStyle>
export const black: StyleProp<TextStyle>
export const deposit-details: StyleProp<TextStyle>
export const copy-text: StyleProp<TextStyle>
export const blog: StyleProp<TextStyle>
export const image: StyleProp<TextStyle>
export const desc: StyleProp<TextStyle>
export const date: StyleProp<TextStyle>
export const read-more: StyleProp<TextStyle>
export const blogpost: StyleProp<TextStyle>
export const btn-share: StyleProp<TextStyle>
export const twitter: StyleProp<TextStyle>
export const google: StyleProp<TextStyle>
export const linkedin: StyleProp<TextStyle>
export const blogpost): StyleProp<TextStyle>
