import { StyleProp, TextStyle } from 'react-native'

export const inner-scroll: StyleProp<TextStyle>
export const content-wrapper: StyleProp<TextStyle>
export const section: StyleProp<TextStyle>
export const pageHead: StyleProp<TextStyle>
export const homeBanner: StyleProp<TextStyle>
export const slick-active: StyleProp<TextStyle>
export const inner-scroll: StyleProp<TextStyle>
export const links: StyleProp<TextStyle>
export const logoImage: StyleProp<TextStyle>
export const slider-arrows: StyleProp<TextStyle>
export const prev-arrow-div,next-arrow-div: StyleProp<TextStyle>
export const prev-arrow-div: StyleProp<TextStyle>
export const reteDetail: StyleProp<TextStyle>
export const media: StyleProp<TextStyle>
export const icon: StyleProp<TextStyle>
export const calculateConvert: StyleProp<TextStyle>
export const calc: StyleProp<TextStyle>
export const nav: StyleProp<TextStyle>
export const active: StyleProp<TextStyle>
export const rateToday: StyleProp<TextStyle>
export const innerBox: StyleProp<TextStyle>
export const col-6: StyleProp<TextStyle>
export const subscribe: StyleProp<TextStyle>
export const withdrawal: StyleProp<TextStyle>
export const nav-link: StyleProp<TextStyle>
export const cardMain: StyleProp<TextStyle>
export const nav-link: StyleProp<TextStyle>
export const cardMain: StyleProp<TextStyle>
export const title: StyleProp<TextStyle>
export const total-balance: StyleProp<TextStyle>
export const inline-buttons: StyleProp<TextStyle>
export const btn: StyleProp<TextStyle>
export const light: StyleProp<TextStyle>
export const btn: StyleProp<TextStyle>
export const minus: StyleProp<TextStyle>
export const plus: StyleProp<TextStyle>
export const contentCard: StyleProp<TextStyle>
export const transferCard: StyleProp<TextStyle>
export const subtitle: StyleProp<TextStyle>
